const RESET_ALL = "0";
const RESET_FOREGROUND = "39";
const RESET_BACKGROUND = "49";

const SET_BOLD = "1";
const SET_DIM = "2";
const SET_ITALIC = "3";
const SET_UNDERLINE = "4";
const SET_SLOW_BLINK = "5";
const SET_RAPID_BLINK = "6";
const SET_REVERSE = "7";
const SET_HIDE = "8";
const SET_STRIKETHROUGH = "9";
const SET_DOUBLE_UNDERLINE = "21";

const RESET_BOLD_DIM = "22";
const RESET_ITALIC = "23";
const RESET_UNDERLINE = "24";
const RESET_BLINK = "25";
const RESET_REVERSE = "27";
const RESET_HIDE = "28";
const RESET_STRIKETHROUGH = "29";

const SET_FG_BLACK = "30";
const SET_FG_RED = "31";
const SET_FG_GREEN = "32";
const SET_FG_YELLOW = "33";
const SET_FG_BLUE = "34";
const SET_FG_MAGENTA = "35";
const SET_FG_CYAN = "36";
const SET_FG_WHITE = "37";

const SET_BG_BLACK = "40";
const SET_BG_RED = "41";
const SET_BG_GREEN = "42";
const SET_BG_YELLOW = "43";
const SET_BG_BLUE = "44";
const SET_BG_MAGENTA = "45";
const SET_BG_CYAN = "46";
const SET_BG_WHITE = "47";

const SET_FG_BRIGHT_BLACK = "90";
const SET_FG_BRIGHT_RED = "91";
const SET_FG_BRIGHT_GREEN = "92";
const SET_FG_BRIGHT_YELLOW = "93";
const SET_FG_BRIGHT_BLUE = "94";
const SET_FG_BRIGHT_MAGENTA = "95";
const SET_FG_BRIGHT_CYAN = "96";
const SET_FG_BRIGHT_WHITE = "97";

const SET_BG_BRIGHT_BLACK = "100";
const SET_BG_BRIGHT_RED = "101";
const SET_BG_BRIGHT_GREEN = "102";
const SET_BG_BRIGHT_YELLOW = "103";
const SET_BG_BRIGHT_BLUE = "104";
const SET_BG_BRIGHT_MAGENTA = "105";
const SET_BG_BRIGHT_CYAN = "106";
const SET_BG_BRIGHT_WHITE = "107";

const SET_FG_COLOR = "38";
const SET_BG_COLOR = "48";

const COLOR_MODE_256 = "5";
const COLOR_MODE_RGB = "2";

const FOREGROUND_INDEX = 0;
const BACKGROUND_INDEX = 1;
const BOLD_DIM_INDEX = 2;
const ITALIC_INDEX = 3;
const UNDERLINE_INDEX = 4;
const BLINK_INDEX = 5;
const REVERSE_INDEX = 6;
const HIDE_INDEX = 7;
const STRIKETHROUGH_INDEX = 8;

module.exports = {
  RESET_ALL,
  RESET_FOREGROUND,
  RESET_BACKGROUND,

  SET_BOLD,
  SET_DIM,
  SET_ITALIC,
  SET_UNDERLINE,
  SET_SLOW_BLINK,
  SET_RAPID_BLINK,
  SET_REVERSE,
  SET_HIDE,
  SET_STRIKETHROUGH,
  SET_DOUBLE_UNDERLINE,

  RESET_BOLD_DIM,
  RESET_ITALIC,
  RESET_UNDERLINE,
  RESET_BLINK,
  RESET_REVERSE,
  RESET_HIDE,
  RESET_STRIKETHROUGH,

  SET_FG_BLACK,
  SET_FG_RED,
  SET_FG_GREEN,
  SET_FG_YELLOW,
  SET_FG_BLUE,
  SET_FG_MAGENTA,
  SET_FG_CYAN,
  SET_FG_WHITE,

  SET_BG_BLACK,
  SET_BG_RED,
  SET_BG_GREEN,
  SET_BG_YELLOW,
  SET_BG_BLUE,
  SET_BG_MAGENTA,
  SET_BG_CYAN,
  SET_BG_WHITE,

  SET_FG_BRIGHT_BLACK,
  SET_FG_BRIGHT_RED,
  SET_FG_BRIGHT_GREEN,
  SET_FG_BRIGHT_YELLOW,
  SET_FG_BRIGHT_BLUE,
  SET_FG_BRIGHT_MAGENTA,
  SET_FG_BRIGHT_CYAN,
  SET_FG_BRIGHT_WHITE,

  SET_BG_BRIGHT_BLACK,
  SET_BG_BRIGHT_RED,
  SET_BG_BRIGHT_GREEN,
  SET_BG_BRIGHT_YELLOW,
  SET_BG_BRIGHT_BLUE,
  SET_BG_BRIGHT_MAGENTA,
  SET_BG_BRIGHT_CYAN,
  SET_BG_BRIGHT_WHITE,

  SET_FG_COLOR,
  SET_BG_COLOR,

  COLOR_MODE_256,
  COLOR_MODE_RGB,

  FOREGROUND_INDEX,
  BACKGROUND_INDEX,
  BOLD_DIM_INDEX,
  ITALIC_INDEX,
  UNDERLINE_INDEX,
  BLINK_INDEX,
  REVERSE_INDEX,
  HIDE_INDEX,
  STRIKETHROUGH_INDEX,
};